### ISSUE TITLE
[JNPCT Adolescent]: Severe Anemia Referrals

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#36]
- [x] To be created in Superset in the Production Environment
- [x] [Requirement Document](https://docs.google.com/spreadsheets/d/1e8lcXyoCZMeewKB4YQXMSMlKwstqIEM9/edit?gid=1178837353#gid=1178837353)

**Comment by adamsanadi6** [comment]
Dashboard link : [[JNPCT Adolescent] Severe Anemia Referrals](https://reporting-superset.avniproject.org/superset/dashboard/140/)

**Comment by adamsanadi6** [comment]
@sachsk / @nupoorkhandelwal Please review the report.

**Comment by nupoorkhandelwal** [comment]
@adamsanadi6 Please update following column names -
1. Refer - Total adolescents who have been referred
2. Not refer - Total adolescents who have been not referred
3. Age - Age (in years)
4. Query would have been more faster if you would have taken latest encounter in a separate CTE instead of joining all the encounters to the final query

**Comment by adamsanadi6** [comment]
@nupoorkhandelwal Changes have been made.
