### ISSUE TITLE
[JNPCT Adolescent]: Update visit schedule cutoff date.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/JNPCT-Adolescent#50]
- [ ] Update visit schedule cutoff date to prevent backdated visits.
- [ ] Date provided by client: 31/08/2024
- [ ] [Link to visit scheduling card](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct-adolescent/48)

**Comment by vedfordev** [comment]
@manish-sd @adamsanadi6  this needs to change on **adjnpctuat**.  As I check it is not available there. I changed it it there. If you have changed else where remove the changes.

**Comment by Dinesh2019** [comment]
if we enroll the individual on 31-aug-2024 then the system will schedule the visit we have raised the bug card for it and the prod team replied 
Root cause: encounters of enrolment not accessible in DEA
Solution: The issue might not occur when entering backdated entries(for the needed use case) since the enrolment date will anyway be before the upload date. So, an encounter will never be scheduled. Dinesh will confirm the same with Anjali.

Refrences video for QA : 

[video link](https://drive.google.com/file/d/10mTWFUtJ96kmdqqqo-ScbEHb0Z4Jg9C7/view?usp=drive_link)
